- name: Change hostnames
  become: true
  hosts: all
  tasks:
    - name: Check /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "{{ ansible_host }}$"
        line: "127.0.0.1 {{ ansible_host }}"
      register: etc_hosts_check
    - name: Check hostname
      ansible.builtin.hostname:
        name: "{{ ansible_host }}"
      register: hostname
    - name: Check if reboot is needed
      set_fact:
        should_reboot: '{{hostname.changed == true or etc_hosts_check.changed == true}}'
    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 300
        connect_timeout: 30
      when: should_reboot == true
    - name: Check hostname changed
      ansible.builtin.shell:
        cmd: hostname
      register: hostname
      failed_when: hostname.stdout != ansible_host
      when: should_reboot == true
- name: Setup Firewall
  become: true
  hosts: all
  tasks:
    - name: Check if ufw is installed
      ansible.builtin.package:
        name: ufw
        state: present
    - name: Setup firewall
      community.general.ufw:
        policy: deny
    - name: Allow SSH
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp
    - name: Allow HTTPS
      community.general.ufw:
        rule: allow
        port: "443"
        proto: tcp
    - name: Allow phpmyadmin
      community.general.ufw:
        rule: allow
        port: "8080"
        proto: tcp
    - name: Enable ufw
      community.general.ufw:
        state: enabled
    - name: Check ufw status
      ansible.builtin.shell:
        cmd: ufw status
      register: ufw
      changed_when: 'ufw.stdout.find("Status: active") == -1'
- name: Setup Docker
  become: true
  hosts: all
  tasks:
    - name: Check if docker is installed
      ansible.builtin.shell:
        cmd: docker --version
      register: docker
      ignore_errors: true
      failed_when: false
      changed_when: false
    - name: Check if needs to install docker
      set_fact:
        install_docker: "{{docker.rc != 0}}" 
    - debug:
        var: install_docker
    - name: Download docker script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/install-docker.sh
        mode: 0755
      when: install_docker == true
    - name: Install docker
      ansible.builtin.shell:
        cmd: /tmp/install-docker.sh
      when: install_docker == true
    - name: Check if docker is installed
      ansible.builtin.shell:
        cmd: docker --version
      register: docker
      when: install_docker == true
    - name: Check if docker-compose is installed
      ansible.builtin.shell:
        cmd: docker compose --version
      register: docker_compose
      when: install_docker == true