services:
  nginx:
    image: nginx
    depends_on:
      - wordpress
    container_name: nginx
    build:
      context: ./requirements/nginx
    env_file: ../.env
    ports:
      - "443:443"
      - "8080:8080"
    networks:
      - cloud1
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - /etc/letsencrypt/:/etc/letsencrypt/

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file: ../.env
    networks:
      - cloud1
      - cloud1-db
    expose:
      - 9000
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    expose:
      - 3306
    env_file: ../.env
    networks:
      - cloud1-db
    healthcheck:
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s
      test: ["CMD", "mysqladmin", "ping", "--silent"]
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb
    expose:
      - 80
    env_file: ../.env
    networks:
      - cloud1
      - cloud1-db
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    name: inception_mariadb
  wordpress_data:
    name: inception_wordpress

networks:
  cloud1-db:
  cloud1: