all:
  hosts:
    h1:
      ansible_host: h1.cloud-1.martiper.me
    h2:
      ansible_host: h2.cloud-1.martiper.me
    h3:
      ansible_host: h3.cloud-1.martiper.me
  vars:
    ansible_user: cloud1
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_private_key_file: "{{lookup('env', 'HOME')}}/.ssh/cloud-1-00_key.pem"